version: '3.8'
services:
  midwa:
    image: totorajo/php-7.4:v1
    container_name: alazka-studio
    ports:
      - "8010:80"
    volumes:
      - .:/var/www/html
    restart: unless-stopped